- set_fact:
    _ingress_vpc_target_group: "{{ cluster_name }}-{{ custom_domain.name }}"

- name: delete the network load balancer
  community.aws.elb_network_lb:
    name: "{{ _ingress_vpc_target_group }}"
    region: "{{ rosa_region }}"
    state: absent
  # no_log: true

- name: delete ingress vpc nlb target group
  community.aws.elb_target_group:
    name: "{{ _ingress_vpc_target_group }}"
    region: "{{ rosa_region }}"
    state: absent
  # no_log: true

