---
- set_fact:
    _cluster_type: "{{ rosa_hosted_cp | ternary('hcp','classic') }}"
  

# tasks file for roles/operator-roles
- name: check for cluster
  ocm_cluster_info:
    name: "{{ cluster_name }}"
  register: _cluster_info
  no_log: true

# oidc provider
- name: get the cert chain from the host
  peer_cert_chain_info:
    host: "{{ oidc_endpoint_url }}"
  register: _oidc_endpoint_chain
  no_log: true

- set_fact:
    _oidc_endpoint_thumbprint: "{{ _oidc_endpoint_chain.ca_thumbprint | replace(':', '') }}"
    _oidc_endpoint: "{{ oidc_endpoint_url.replace('https://', '') }}"



#https://mobb.ninja/docs/rosa/kms/ 
#Create just the operator roles

- when: _cluster_type == 'classic'
  block:
    - with_items: "{{ operator_roles[_cluster_type] }}"
      include_tasks: roles.yml

    - set_fact:
        ebs_csi_arn: "{{ _cluster_info.cluster.aws.sts.operator_iam_roles | selectattr('name','match','ebs-cloud-credentials') | map(attribute='role_arn') | first }}"

    - set_fact:
        kms_key_id: "{{ rosa_kms_key_arn[-36:]  }}"

    - name: Creating KMS policy template
      ansible.builtin.template:
        src: kms/kms-policy.json
        dest: /tmp/kms-policy.json
  
    - name: Creating KMS policy in aws
      ansible.builtin.command: aws kms put-key-policy --key-id {{ kms_key_id }} --policy file:///tmp/kms-policy.json --policy-name default
      register: output

     






#Create just the oidc provider
- when: _cluster_type == 'classic'
  block:
    - name: create oidc provider for cluster
      oidc_provider:
        url: "{{ oidc_endpoint_url }}"
        client_ids: ["openshift", "sts.amazonaws.com"]
        thumbprints: "{{ _oidc_endpoint_thumbprint }}"
        tags:
          rosa_cluster_id: "{{ cluster_id }}"
      register: _oidc_provider_info

    



- when: _cluster_type == 'hcp'
  block:
    - name: create oidc provider for cluster
      oidc_provider:
        url: "{{ oidc_endpoint_url }}"
        client_ids: ["openshift", "sts.amazonaws.com"]
        thumbprints: "{{ _oidc_endpoint_thumbprint }}"
        tags:
          red-hat-managed: "true"
      register: _oidc_provider_info

    - set_fact:
        oidc_id: "{{ _cluster_info.cluster.aws.sts.oidc_config.id }}"
      when: (oidc_id is not defined) or (oidc_id == '')

    - name: create operator roles for HCP clusters
      command: |
        rosa create operator-roles --hosted-cp --mode auto --yes \
          --prefix "{{ cluster_name }}" \
          --oidc-config-id "{{ oidc_id }}" \
          --installer-role-arn "arn:aws:iam::{{ aws_account_id }}:role/{{ rosa_account_roles_prefix }}-Installer-Role"


