---
- name: Create a new transit gateway using defaults
  ec2_transit_gateway:
    state: present
    region: "{{ rosa_region }}"
    description: "rosa {{ cluster_name }} transit gateway"
    dns_support: yes
    tags: "{{ extra_tags | combine({'Name': 'rosa-' + cluster_name + '-tgw' }) }}"
    auto_associate: yes
    auto_propagate: yes
    # auto_attach: no
  register: _tgw

- set_fact:
    tgw_id: "{{ _tgw.transit_gateway.transit_gateway_id }}"
    tgw_arn: "{{ _tgw.transit_gateway.transit_gateway_arn }}"
    tgw_route_table: "{{ _tgw.transit_gateway.options.association_default_route_table_id }}"

