---
# tasks file for rosa_dns_resolver

- set_fact:
    _cluster_dns: "{{ rosa_dns_resolver.zone }}"

- name: "run rosa_cluster present tasks"
  import_tasks: present/main.yml
  when: state == 'present'

- name: "run rosa_cluster absent tasks"
  import_tasks: absent/main.yml
  when: state == 'absent'
