cluster_name: ansible-rosa-pl

rosa_private_link: true
rosa_sts: true

#uncomment to add a custom kms key arn
rosa_kms_key_arn: "arn:aws:kms:us-east-2:976249332110:key/1c5a1b23-96c4-4628-a6ea-e229ef216d9c" 

# uncomment to pin to a version
# rosa_version: 4.13.10
rosa_region: us-east-2
rosa_vpc_cidr: "10.0.0.0/16"
rosa_compute_machine_type: m5.xlarge

rosa_multi_az: true
# jumphost_ami: ami-0ba62214afa52bec7
# jumphost_ami: ami-07b1d7739c91ed3fc
# jumphost_instance_type: t1.micro
jumphost_instance_type: t2.micro
# jumphost_instance_type: m4.large

rosa_create_admin: true
