cluster_name: ans-rosa-hcp
# rosa_disable_workload_monitoring: true
rosa_private_link: false
# note private-link forces private to be true
# regardless of the following value.
rosa_private: false
rosa_sts: true
# rosa_min_replicas: 3
# rosa_max_replicas: 6
rosa_hosted_cp: true
# uncomment to pin to a version
rosa_version: 4.14.6

rosa_region: us-east-1
rosa_vpc_cidr: "10.0.0.0/20"
rosa_compute_machine_type: m5.xlarge

rosa_create_admin: true
rosa_multi_az: true

# uncomment to enable custom kms workflow
# rosa_kms_key_arn: "" #arn:aws:kms:us-east-2:<redacted>:key/<redacted>

extra_tags:
  cost-center: CC468
  service-phase: lab
  app-code: MOBB-001
  owner: "{{ ansible_user_id }}@redhat.com"
