---

- include_tasks: validate.yml

- when:
    - aws_account_id is not defined
    - rosa_sts | bool
  block:
    - name: get aws caller info for accountid
      aws_caller_info:
      register: _aws_caller_info

    - set_fact:
        aws_account_id: "{{ _aws_caller_info.account }}"

- fail:
    msg: |
      rosa_account_roles_prefix must end in "-HCP-ROSA" for Hosted Control Plane Clusters
      rosa_account_roles_prefix currently set to: "{{ rosa_account_roles_prefix }}"
  when:
    - rosa_account_roles_prefix is not search("^.*-HCP-ROSA$")
    - rosa_hosted_cp | bool
