- fail:
    msg: "Do not use mint mode, 'rosa_sts` must be set to True"
  when: not rosa_sts | bool
- fail:
    msg: "proxy_enabled can only be enabled if rosa_private_link is enabled"
  when:
    - (not rosa_private_link | bool) and
      (proxy_enabled | default(False) | bool)

