---
# tasks file for roles/account-roles

- set_fact:
    _ocp_version: "{{ rosa_version | regex_search('^[0-9]+\\.[0-9]+') }}"

- when: rosa_account_roles_prefix != "ManagedOpenShift"
  block:
    - include_tasks: classic.yml
      when: not rosa_hosted_cp | default('False') | bool

    - include_tasks: hcp.yml
      when: rosa_hosted_cp | default('False') | bool
