cluster_name: ansible-rosa

rosa_private_link: false
# note private-link forces private to be true
# regardless of the following value.
rosa_private: false
rosa_sts: true
rosa_enable_autoscaling: true
rosa_min_replicas: 2
rosa_max_replicas: 4

# uncomment to pin to a version
# rosa_version: 4.13.10
rosa_region: us-east-1
rosa_vpc_cidr: "10.0.0.0/16"
rosa_compute_machine_type: m5.xlarge

rosa_create_admin: true

# uncomment to enable custom kms workflow
# rosa_kms_key_arn: "" #arn:aws:kms:us-east-2:<redacted>:key/<redacted>