---
- pause:
    seconds: 5
    prompt: |
      the rh_mobb {{ role_name }} role is being deprecated for the
      more modular rh_mobb rosa_vpc role.  Consider switching.

- include_role:
    name: rosa_vpc
  vars:
    state: present
    rosa_vpc:
      name: "rosa-{{ cluster_name }}-vpc"
      region: "{{ rosa_region }}"
      cidr: "{{ rosa_vpc_cidr }}"
      tgw_id: "{{ tgw_id | default('')}}"
      private_subnets: "{{ rosa_vpc_private_subnets }}"
      public_subnets: "{{ rosa_vpc_public_subnets }}"
      extra_tags: "{{ extra_tags }}"
