# calculate network CIDRs for multi AZ clusters
- block:
    - set_fact:
        _cidr: "{{ (rosa_vpc_cidr | ansible.utils.ipaddr('prefix')) + 6 }}"
    - set_fact:
        rosa_vpc_public_subnets:
          - cidr: "{{ rosa_vpc_cidr | ansible.utils.ipsubnet(_cidr, 0) }}"
            az: "{{ rosa_region }}a"
          - cidr: "{{ rosa_vpc_cidr | ansible.utils.ipsubnet(_cidr, 1) }}"
            az: "{{ rosa_region }}b"
          - cidr: "{{ rosa_vpc_cidr | ansible.utils.ipsubnet(_cidr, 2) }}"
            az: "{{ rosa_region }}c"
      when: rosa_vpc_public_subnets is not defined
    - set_fact:
        rosa_vpc_private_subnets:
          - cidr: "{{ rosa_vpc_cidr | ansible.utils.ipsubnet(_cidr, 3) }}"
            az: "{{ rosa_region }}a"
          - cidr: "{{ rosa_vpc_cidr | ansible.utils.ipsubnet(_cidr, 4) }}"
            az: "{{ rosa_region }}b"
          - cidr: "{{ rosa_vpc_cidr | ansible.utils.ipsubnet(_cidr, 5) }}"
            az: "{{ rosa_region }}c"
      when: rosa_vpc_private_subnets is not defined
  when:
    - rosa_multi_az | bool

# calculate network CIDRs for single AZ clusters
- block:
    - set_fact:
        _cidr: "{{ (rosa_vpc_cidr | ansible.utils.ipaddr('prefix')) + 2 }}"
    - set_fact:
        rosa_vpc_public_subnets:
          - cidr: "{{ rosa_vpc_cidr | ansible.utils.ipsubnet(_cidr, 0) }}"
            az: "{{ rosa_region }}a"
            resource_tags: { "Name":"{{ cluster_name }}-public" }
      when: rosa_vpc_public_subnets is not defined
    - set_fact:
        rosa_vpc_private_subnets:
          - cidr: "{{ rosa_vpc_cidr | ansible.utils.ipsubnet(_cidr, 1) }}"
            az: "{{ rosa_region }}a"
            resource_tags: { "Name":"{{ cluster_name }}-private" }
      when: rosa_vpc_private_subnets is not defined
  when:
    - not (rosa_multi_az | bool)

# - debug:
#     msg: |
#       ---
#       # rosa_vpc_public_subnets
#       {{ rosa_vpc_public_subnets | to_yaml }}
#       ---
#       # rosa_vpc_private_subnets
#       {{ rosa_vpc_private_subnets | to_yaml }}
