---
# tasks file for rosa_ec2_instance

- name: "run rosa_ec2_instance present tasks"
  import_tasks: present/main.yml
  when: state == 'present'

- name: "run rosa_ec2_instance absent tasks"
  import_tasks: absent/main.yml
  when: state == 'absent'
