---
# defaults file for rosa_cluster

rosa_cluster:
  name: rosa-cluster
  subnet_ids: []
  # http_proxy: http://{{ proxy_private_ip }}:3128
  # https_proxy: http://{{ proxy_private_ip }}:3128
  # no_proxy: ~
  # additional_trust_bundle_file: "roles/proxy_create/files/squid-ca-cert.pem"
  disable_workload_monitoring: false
  aws_account_id: ~
  account_roles_prefix: Managed-OpenShift
  region: us-east-2
  private_link: false
  vpc_cidr: 10.0.0.0/20
  multi_az: false
  version: 4.14.6
  hosted_cp: false
  autoscaling: false
  min_replicas:
  max_replicas:
  compute_nodes: # 3 for multi-az, 2 for single-az
  compute_machine_type: "m5.xlarge"
  role_arn:
  support_role_arn:
  controlplane_iam_role:
  worker_iam_role:
  operator_roles_prefix:
  kms_key_arn:
  tags: {}
  wait: true


