---
- pause:
    seconds: 5
    prompt: |
      the rh_mobb {{ role_name }} role is being deprecated for the
      more modular rh_mobb rosa_account_roles role.  Consider switching.

- include_role:
    name: rosa_account_roles
  vars:
    state: absent
    rosa_account_roles:
      hosted_cp: "{{ rosa_hosted_cp }}"
      version: "{{ rosa_account_roles_version }}"
      prefix: "{{ rosa_account_roles_prefix }}"
