---
name: Release
on:
  push:
    tags:
      - '*'

jobs:
  galaxy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and Release
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.ANSIBLE_GALAXY_API_TOKEN }}'
          galaxy_version: '${{ env.RELEASE_VERSION }}'
          build: true
          publish: true
