---
# tasks file for rosa_transit_gateway

- name: "run rosa_transit_gateway present tasks"
  import_tasks: present/main.yml
  when: state == 'present'

- name: "run rosa_transit_gateway absent tasks"
  import_tasks: absent/main.yml
  when: state == 'absent'
